name = "flutter"
type = "cli"

[resolve]
git-url = "https://github.com/flutter/flutter"

[platform.linux]
download-file = "{version}.tar.gz"

[platform.macos]
download-file = "{version}.tar.gz"

[platform.windows]
download-file = "{version}.zip"

[install]
download-url = "https://github.com/flutter/flutter/archive/refs/tags/{download_file}"
https://github.com/flutter/flutter/archive/refs/tags/3.19.0-0.1.pre.zip
